### ISSUE TITLE
Along these lines, fix external links too?

### ISSUE THREAD

**Issue by chryton** [Mte90/FB-Android-Crash#4]
"Open in external browser" also breaks almost 100% of the time with me having to go back to Facebook and hit the link again so I can go to the actual link rather than some FB internal link which breaks.

**Comment by Mte90** [comment]
This is only an example of the integrated browser sucks instead the android ones like Chrome or Firefox.
The issue on that integrated that is impossible to debug and find the issue is very difficult, I find that an iframe with the src of an image in base64 crash the browser.

**Comment by chryton** [comment]
@Mte90 What I am talking about is not an issue of the external browsers, it is the fact that the Facebook links themselves are also broken when trying to direct you outwards because either they are making the erroneous assumption that people are not using the external browser or they don't have a tracking redirect setup correctly.

**Comment by chryton** [comment]
Though i entirely agree with you that the internal browser is jank; hence why I started not using it.

**Comment by Mte90** [comment]
uhm I am not using the internal browser but a customer need the support so my journey started XD
I think that they do a tracking with a redirect in the url like they do on the desktop version (I done a browser extension to avoid that).
I'm curious about the behaviour on twitter integrated browser but I didn't tested on it.
