### ISSUE TITLE
fb-messenger:// links don't work either

### ISSUE THREAD

**Issue by jakst** [Mte90/FB-Android-Crash#7]
Another issue with their browser is that they cannot even open intents to their own app. I have a share to messenger which breaks completely in facebooks browser only, on  both iOS and Android. Has any one had this problem as well?

Example code
`<a href=”fb-messenger://share/?link= https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fsharing%2Freference%2Fsend-dialog&app_id=123456789”>Send In Messenger</a>`

Taken from
https://developers.facebook.com/docs/sharing/messenger/

**Comment by Mte90** [comment]
A good news....
A more proof that they are not so very android based or mobile based...
